name: sample
on: push

jobs:
  build:
    name: gin
    runs-on: ubunts-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: check out
        uses: actions/checkout@v1

      - name: download
        run: go get -v -t -d ./...

      - name: install lint
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0

      - name: lint
        run: golangci-lint run

      - name: test
        run: go test ./... -v