name: workflow
on: push

jobs:
  build:
    name: gin
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: check out
        uses: actions/checkout@v1

      - name: download
        run: go get -v -t -d ./...

      - name: install lint
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.0
          sudo mv ./bin/golangci-lint $GOPATH/bin/

      - name: lint
        run:  golangci-lint run --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck --enable=staticcheck ./...

      - name: test
        run: go test ./... -v